all: sfml-app

clean:
	-rm -f main.o sfml-app

sfml-app: main.o
	g++ main.o -o sfml-app -L/opt/homebrew/Cellar/sfml/2.6.1/lib -lsfml-graphics -lsfml-window -lsfml-system

main.o: main.cpp
	g++ -c -I/opt/homebrew/Cellar/sfml/2.6.1/include  main.cpp

